
# Project name, version, and profile (configured in profiles.yml)
# Full documentation: https://docs.getdbt.com/docs/dbt-project-yml
name: 'carmen_dbt'
version: '1.0.0'

profile: 'carmen_dbt'

# Paths in which files are located
# Full documentation: https://docs.getdbt.com/docs/dbt-project-yml#paths
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["docs"]

# Cleans these folders when running `dbt clean`
# Full documentation: https://docs.getdbt.com/docs/dbt-project-yml#clean-targets
clean-targets:
  - "target"
  - "dbt_packages"

# Model folders within the project and their materialization overhauls
models:
  carmen_dbt:
  # Marts materliaze as tables for reporting and analysis
    mart:
      +materialized: table
  # Staging models materialize as tables for performance and easy cleaning (or joining in this case)
    staging:
      +materialized: view
seeds:
  carmen_dbt:
    +schema: sources

# Dbt cloud configuration
# Full documentation: https://docs.getdbt.com/docs/dbt-cloud/dbt-cloud-cli
dbt-cloud:
    project-id: 70471823463035
